name-template: "$NEXT_PATCH_VERSION 🌈"
tag-template: "$NEXT_PATCH_VERSION"
categories:
  - title: "Breaking changes:"
    labels:
      - "breaking change"
template: |
  ## Merged pull requests:

  $CHANGES
