sudo: required
language: python
cache: pip
python:
  - "3.4"
  - "3.5"
# Enable 3.7 without globally enabling dist: xenial for other build jobs
matrix:
  include:
    - python: 3.6
      dist: xenial
    - python: 3.7
      dist: xenial
# command to install dependencies
install: pip install -U tox-travis
# command to run tests
script: tox
