sudo: false
language: python
python:
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  # nightly now points to 3.7-dev,
  # which is not supported by latest released tox version
  - "3.6-dev"
# command to install dependencies
install: pip install tox-travis
# command to run tests
script: tox
