sudo: false
language: python
cache: pip
python:
  - "3.4"
  - "3.5"
  - "3.5-dev"
  - "3.6"
  - "3.6-dev"
  # nightly now points to 3.7-dev,
  # which is not supported by latest released tox version
# command to install dependencies
install: pip install -U tox-travis
# command to run tests
script: tox
